apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: techchallenge
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/healthcheck-port: '3000'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin123"
            - name: GF_SERVER_ROOT_URL
              # Ajuste do root URL para funcionar com API Gateway e subpath
              value: "/grafana/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SMTP_ENABLED
              value: "true"
            - name: GF_SMTP_HOST
              value: smtp.gmail.com:587
            - name: GF_SMTP_USER
              value: piresalex161@gmail.com
            - name: GF_SMTP_PASSWORD
              value: jarbdqwyhfesaryn
            - name: GF_SMTP_FROM_ADDRESS
              value: piresalex161@gmail.com
          volumeMounts:
            - name: provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: provisioning-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: provisioning-alerting # ADICIONE ESTA LINHA
              mountPath: /etc/grafana/provisioning/alerting
              readOnly: true
            - name: dashboard-json-files
              mountPath: /var/lib/grafana/dashboards
              readOnly: true
      volumes:
        - name: provisioning-datasources
          configMap:
            name: grafana-provisioning-datasources
        - name: provisioning-dashboards-config
          configMap:
            name: grafana-provisioning-dashboards
        - name: provisioning-alerting # ADICIONE ESTA LINHA
          configMap:
            name: grafana-alerting-provisioning
        - name: dashboard-json-files
          configMap:
            name: grafana-dashboards-json-files
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: techchallenge
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP