apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-app-deployment
  namespace: techchallenge
  labels:
    app.kubernetes.io/name: techchallenge-app
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: techchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: techchallenge-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: techchallenge-app
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: techchallenge
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: techchallenge-app
          image: public.ecr.aws/z0l6i1e3/techchallenge-12soat/api:monitoramento
          imagePullPolicy: Always # Ensures we always get the latest version
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 120
            periodSeconds: 15
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: techchallenge-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: techchallenge-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_APPLICATION_NAME
              value: "techchallenge-app"
            - name: SPRING_LIQUIBASE_CHANGE-LOG
              value: "classpath:liquibase/liquibase-changelog.yml"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "1.5Gi"