apiVersion: v1
kind: Service
metadata:
  name: techchallenge-service
  namespace: techchallenge
  annotations:
    # Configura o Health Check apenas para este Target Group
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
    alb.ingress.kubernetes.io/healthcheck-port: '8080'
spec:
  selector:
    app.kubernetes.io/name: techchallenge-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
