apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-app-deployment
  namespace: techchallenge
  labels:
    app.kubernetes.io/name: techchallenge-app
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: techchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: techchallenge-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: techchallenge-app
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: techchallenge
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: techchallenge-app
          image: public.ecr.aws/z0l6i1e3/techchallenge-12soat/api:latest
          imagePullPolicy: Always # Ensures we always get the latest version
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 120
            periodSeconds: 15
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_APPLICATION_NAME
              value: "techchallenge-app"
            - name: SPRING_LIQUIBASE_CHANGE-LOG
              value: "classpath:liquibase/liquibase-changelog.yml"
            - name: SPRING_CONFIG_LOCATION
              value: "file:/etc/config/application.properties"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "1.5Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - name: app-config
              mountPath: "/etc/config"
              readOnly: true
      initContainers:
        - name: init-secrets
          image: alpine/helm:latest
          command: ['sh', '-c', 'set -ex;
            SECRET_FILE="/mnt/secrets-store/techchallenge-credentials-json";
            DB_PWD=$(cat "$SECRET_FILE" | jq -r '.DB_PASSWORD');
            SPRING_MAIL_USERNAME=$(cat "$SECRET_FILE" | jq -r '.SPRING_MAIL_USERNAME');
            SPRING_MAIL_PASSWORD=$(cat "$SECRET_FILE" | jq -r '.SPRING_MAIL_PASSWORD');
            {
              echo "spring.datasource.url=jdbc:postgresql://techchallenge-db.crwcmi44cymk.sa-east-1.rds.amazonaws.com:5432/postgres";
              echo "spring.datasource.username=postgres";
              echo "spring.datasource.password=$DB_PWD";
              echo "spring.mail.host=smtp.gmail.com";
              echo "spring.mail.port=587";
              echo "spring.mail.protocol=smtp";
              echo "spring.mail.username=$SPRING_MAIL_USERNAME";
              echo "spring.mail.password=$SPRING_MAIL_PASSWORD";
              echo "spring.mail.properties.mail.smtp.auth=true";
              echo "spring.mail.properties.mail.smtp.starttls.enable=true";
            } > /etc/config/application.properties']
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - name: app-config
              mountPath: "/etc/config"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets-manager-secret-provider
        - name: app-config
          emptyDir: {}

