apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-app-deployment
  namespace: techchallenge
  labels:
    app.kubernetes.io/name: techchallenge-app
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: techchallenge
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: techchallenge-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: techchallenge-app
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: techchallenge
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: techchallenge-app
          image: public.ecr.aws/z0l6i1e3/techchallenge-12soat/api:latest
          imagePullPolicy: Always # Ensures we always get the latest version
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 60
            periodSeconds: 15
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_APPLICATION_NAME
              value: "techchallenge-app"
            - name: SPRING_LIQUIBASE_CHANGE-LOG
              value: "classpath:liquibase/liquibase-changelog.yml"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://techchallenge-db.crwcmi44cymk.sa-east-1.rds.amazonaws.com:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: techchallenge-secrets
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: techchallenge-secrets
                  key: SPRING_MAIL_PASSWORD
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1.5Gi"
      volumes:
        - name: techchallenge-secrets-volume
          secret:
            secretName: techchallenge-secrets
