apiVersion: v1
kind: Service
metadata:
  name: techchallenge-service
  namespace: techchallenge
  labels:
    app.kubernetes.io/name: techchallenge-app
    app.kubernetes.io/part-of: techchallenge
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: techchallenge-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080