apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: techchallenge
  name: techchallenge-hpa
  labels:
    app.kubernetes.io/name: techchallenge-app
    app.kubernetes.io/part-of: techchallenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techchallenge-app-deployment
  minReplicas: 1
  maxReplicas: 2 # Max num of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 # When CPU average usage hits 80% triggers the scalability
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 # When memory usage hits 80% triggers the scalability
