apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techchallenge-ingress
  namespace: techchallenge
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
spec:
  rules:
  - http:
      paths:
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: techchallenge-service
            port:
              number: 8080
      - path: /api-docs
        pathType: Prefix
        backend:
          service:
            name: techchallenge-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: techchallenge-service
            port:
              number: 8080
