apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - configmap.yml
  - app-deployment.yaml
  - app-service.yaml
  - hpa.yaml
  - monitoring/grafana.yaml
  - monitoring/prometheus.yaml
