apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-nginx-proxy
  namespace: techchallenge
data:
  default.conf: |
    server {
      listen 8080;
    
      # Captura tudo que vem com /grafana/ e manda para a raiz do Grafana
      location /grafana/ {
        proxy_pass http://127.0.0.1:3000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    
      # Healthcheck do ALB (caso ele bata na raiz)
      location /api/health {
        proxy_pass http://127.0.0.1:3000/api/health;
      }
    }