apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: techchallenge
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-v1
    app.kubernetes.io/part-of: techchallenge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-v1
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432