apiVersion: v1
kind: Secret
metadata:
  name: techchallenge-secrets
  namespace: techchallenge
  labels:
    app.kubernetes.io/part-of: techchallenge
type: Opaque
data:
  #todo change the AWS secrets
  # Base64 encoded values. Replace these with your actual AWS keys!
  AWS_ACCESS_KEY_ID: Q0hBTkdFX01FCg==
  AWS_SECRET_ACCESS_KEY: Q0hBTkdFX01FCg==
  # Database details (used as fallback or for reference)
  DB_NAME: dGVjaGNoYWxsZW5nZQ==
  DB_USR: cG9zdGdyZXM=
  DB_PWD: NntqSjlINld7RQ==
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vdGVycmFmb3JtLTIwMjYwMTA3MDEzODIxOTc5NTAwMDAwMDAzLmM0bjBraXd1MjUzeS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi90ZWNoY2hhbGxlbmdl