apiVersion: v1
kind: Secret
metadata:
  name: techchallenge-secrets
  namespace: techchallenge
  labels:
    app.kubernetes.io/part-of: techchallenge
type: Opaque
data:
  DB_NAME: cG9zdGdyZXM=
  DB_USR: cG9zdGdyZXM=
  DB_PWD: cGFzc3dvcmQ=
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vdGVjaGNoYWxsZW5nZS1kYi5jcndjbWk0NGN5bWsuc2EtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvcG9zdGdyZXM=