apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager-secret-provider
  namespace: techchallenge
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "techchallenge-credentials"
        objectType: "secretsmanager"
        objectAlias: "techchallenge-credentials-json"