apiVersion: v1
kind: Secret
metadata:
  name: techchallenge-secrets
  namespace: techchallenge
  labels:
    app.kubernetes.io/part-of: techchallenge
type: Opaque
stringData:
  DB_NAME: "postgres"
#  DB_USR: "postgres"
#  DB_URL: "jdbc:postgresql://postgres-service:5432/postgres"
  DB_PWD: "cGFzc3dvcmQ=" # Substitua pelo valor em Base64
  SPRING_MAIL_USERNAME: "cGlyZXNhbGV4MTYxQGdtYWlsLmNvbQ==" # Substitua pelo valor em Base64
  SPRING_MAIL_PASSWORD: "amFyYmRxd3loZmVzYXJ5bg==" # Substitua pelo valor em Base64
