apiVersion: v1
kind: Secret
metadata:
  name: techchallenge-secrets
  labels:
    app.kubernetes.io/part-of: techchallenge
type: Opaque
stringData:
  DB_NAME: "postgres"
  DB_USR: "postgres"
  DB_PWD: "password"
  DB_URL: "jdbc:postgresql://postgres-service:5432/postgres"
