name: pipeline

on:
  push:
    branches: [ main, develop, 'release/*' ]
  pull_request:
    branches: [ main, develop, 'release/*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Set up JDK 21 and Cache Maven packages
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
  
      - name: Run Build and Tests
        run: mvn -B verify
  
      - name: Upload workspace for subsequent jobs
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  code-analysis:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
  
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
  
      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AlexPires1_techchallenge-12SOAT

  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: code-analysis
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download application artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar

      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B deploy -DskipTests


  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/develop' && 'stg') || 'pre' }}
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/release')
    steps:
      - name: Deploy to ${{ environment.name }}
        run: echo "Deploying artifact to environment..."

  post-deploy-tests:
    name: Post-Deploy Validation Tests
    runs-on: ubuntu-latest
    needs: deploy
    if: success() && (github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Smoke Tests
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release')
        run: sh 'src/main/scripts/smoktest.sh'

      - name: Run Integration Tests
        if: github.ref == 'refs/heads/develop'
        run: sh 'src/main/scripts/testeIntegrados.sh'

      - name: Run Functional Tests
        if: startsWith(github.ref, 'refs/heads/release')
        run: sh 'src/main/scripts/testeFuncionais.sh'
